name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     with:
       fetch-depth: 0
     - name: Deploy
     env:
       HEROKU_API_KEY: ${{secrets.37aae3dd-f19a-456d-ac2e-55b2ab045b5b}}
       HEROKU_APP_NAME: "protected-gorge-80241"
Heroku app.
     run: git push -f
https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
